# Generated by Django 6.0.3 on 2026-03-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('penulis', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
                ('jenis', models.CharField(choices=[('fiksi', 'Fiksi'), ('teknik', 'Teknik'), ('sains', 'Sains'), ('bisnis', 'Bisnis'), ('sejarah', 'Sejarah'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('tahun_terbit', models.PositiveIntegerField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('stok', models.PositiveIntegerField(default=1)),
                ('tanggal_ditambahkan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Buku',
                'verbose_name_plural': 'Buku',
                'ordering': ['-tanggal_ditambahkan'],
            },
        ),
    ]
