# Generated by Django 6.0.3 on 2026-03-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='file_buku',
            field=models.FileField(blank=True, null=True, upload_to='buku/'),
        ),
        migrations.AddField(
            model_name='buku',
            name='format_file',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('epub', 'EPUB')], max_length=10, null=True),
        ),
    ]
